#!/bin/sh

DIALOG_RESULT=$(echo -e 'shutdown\nsleep\nreboot\nlogout' | rofi -dmenu -i -p "power options" -hide-scrollbar -lines 4 )

echo "This result is : $DIALOG_RESULT"

if [ "$DIALOG_RESULT" = "logout" ]; then
    i3-msg 'exit'
elif [ "$DIALOG_RESULT" = "reboot" ]; then
    exec reboot
elif [ "$DIALOG_RESULT" = "shutdown" ]; then
    exec shutdown -h now
elif [ "$DIALOG_RESULT" = "sleep" ]; then
    exec systemctl suspend
fi
