#!/bin/sh

DIALOG_RESULT=$(echo -e 'cancel\nshutdown\nreboot\nlogout' | rofi -dmenu -i -p "power options" -hide-scrollbar -lines 4 )

echo "This result is : $DIALOG_RESULT"
sleep 1;

if [ "$DIALOG_RESULT" = "logout" ];
then
    i3-msg 'exit'
elif [ "$DIALOG_RESULT" = "reboot" ];
then
    exec reboot
elif [ "$DIALOG_RESULT" = "shutdown" ];
then
    exec shutdown -h now
fi
