#!/bin/bash
# changeVolume
# e.g. use : changeVolume increase 5
#            changeVolume decrease 5
#            changeVolume toggle-mute
#            changeVolume mute
#            changeVolume unmute

# Arbitrary but unique message id
msgId="991049"
  
# Change the volume using alsa(might differ if you use pulseaudio)
pamixer --"$@" > /dev/null
 
# Query amixer for the current volume and whether or not the speaker is muted
volume="$(pamixer --get-volume)"
mute="$(pamixer --get-mute)"
if [[ $volume == 0 || "$mute" == "true" ]]; then
     # Show the sound muted notification
     dunstify -a "changeVolume" -u low -i audio-volume-muted -r "$msgId" "Volume muted" 
else
     # select icon
     volume=$(expr $volume + 0)
     if [[ $volume -lt 35 ]]; then
        icon="audio-volume-low"
     elif [[ $volume -gt 75 ]]; then
        icon="audio-volume-high"
     else
        icon="audio-volume-medium"
     fi
     # Show the volume notification
     dunstify -a "changeVolume" -u low -i "$icon" -r "$msgId" \
     "Volume: ${volume}%" "$(~/.config/dunst/getProgressString 10 "<b> </b>" " " $volume)"
fi
 
# Play the volume changed sound
canberra-gtk-play -i audio-volume-change -d "changeVolume"
