swipe:
  4:
    left:
      command: 'ydotool key super+ctrl+left'
    right:
      command: 'ydotool key super+ctrl+right'
  3:
    left: 
      command: 'ydotool key alt+Right'
    right: 
      command: 'ydotool key alt+Left'
    up: 
      command: 'ydotool key shift+plus'
    down: 
      command: 'ydotool key shift+minus'
pinch:
  in:
    command: 'ydotool key ctrl+Plus'
  out:
    command: 'ydotool key ctrl+minus'

threshold:
  swipe: 0.5
  pinch: 0.2

interval:
  swipe: 0.2
  pinch: 0.2
